# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['monero:45F2bNHVcRzXVBsvZ5giyvKGAgm6LFhMsjUUVPTEtdgJJ5SNyxzSNUmFSBR5qCCWLpjiUjYMkmZoX9b3cChNjvxR7kvh436', 'bitcoin:3MMKHXPQrGHEsmdHaAGD59FWhKFGeUsAxV', 'ethereum:0xeA4DA3F9BAb091Eb86921CA6E41712438f4E5079', 'litecoin:MBfrxLJMuw26hbVi2MjCVDFkkExz8rYvUF', ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
